### PR TITLE
Fix trackDetailsFromSDP not handling fec ssrc

### LINKED ISSUE #3109: trackDetailsFromSDP should also black list FEC ssrc
## The Problem

Unified plan SDP can contain FEC and RTX tracks in the same m= with video track, https://datatracker.ietf.org/doc/html/draft-roach-mmusic-unified-plan-00#section-4.5 .
But currently, pion's implementation thinks it's plan B sdp if FEC track is included.

## The Cause

It seems like the problem is in function `trackDetailsFromSDP` of sdp.go, it only black lists rtx ssrc, but not fec ssrc.

## The Fix

We should also black list fec ssrc in `trackDetailsFromSDP`. And also test `descriptionIsPlanB` against examples in https://datatracker.ietf.org/doc/html/draft-roach-mmusic-unified-plan-00#section-4 .

### PR DESCRIPTION
**Pull request by 3DRX**
fix #3109 

TODO
- [x] Add test
- [x] Use consts defined in https://github.com/pion/sdp/pull/210, instead of using string literals

### CODE REVIEW

**Comment by 3DRX** [comment]
I started to work on FEC in pion as a receiver, for now this PR doesn't provide any additional capabilities (and hopefully doesn't break anything too), but imo removes one of the road blocks toward the goal.

File: sdp_test.go [hunk 1]
```diff
@@ -454,6 +454,44 @@ func TestTrackDetailsFromSDP(t *testing.T) {
...
+		if track.rtxSsrc == nil {
+			assert.Fail(t, "missing RTX ssrc for video track")
+		} else {
+			assert.Equal(t, SSRC(4000), *track.rtxSsrc)
+		}
+		if track.fecSsrc == nil {
+			assert.Fail(t, "missing FEC ssrc for video track")
+		} else {
+			assert.Equal(t, SSRC(5000), *track.fecSsrc)
+		}
```
Comment (aalekseevx) [inline sdp_test.go:492]: maybe use [require.NotNil](https://pkg.go.dev/github.com/stretchr/testify/require#NotNil)?

**Review by aalekseevx — APPROVED** [review]
Looks good to me!

File: sdp_test.go (hunk 1 above)
Comment (aalekseevx) [reply sdp_test.go]: @3DRX, I think there's a panic possible now as `assert` doesn't stop execution. wdyt of using require.NotNil?

Comment (3DRX) [reply sdp_test.go]: Oops, my bad, it's fixed now.
