### PR TITLE
Fixes for pre-added recvonly transceivers

### LINKED ISSUE #1722: AddTrack fails after the initial sendonly transceiver is created in a negotiation initiated by remote peer
### Your environment.
  - Version: master / v3.0.16 / 3db47301668ea709df4970812974d7baf124300b
  - Browser: N/A

### What did you do?

The following tests I just wrote fail:

```go
// Assert the following behaviors:
// - Offerer can add a recvonly transceiver
// - During negotiation, answerer peer adds an inactive (or sendonly) transceiver
// - Answerer can add a track to the existing sendonly transceiver
// - Offerer can receive the RTP packets.
func TestPeerConnection_Renegotiation_AddRecvonlyTransceiver_Then_Recv(t *testing.T) {
	lim := test.TimeOut(time.Second * 30)
	defer lim.Stop()

	report := test.CheckRoutines(t)
	defer report()

	pcOffer, pcAnswer, err := newPair()
	if err != nil {
		t.Fatal(err)
	}

	_, err = pcOffer.AddTransceiverFromKind(
		RTPCodecTypeVideo,
		RtpTransceiverInit{
			Direction: RTPTransceiverDirectionRecvonly,
		},
	)
	assert.NoError(t, err)

	assert.NoError(t, signalPair(pcOffer, pcAnswer))

	localTrack, err := NewTrackLocalStaticSample(
		RTPCodecCapability{MimeType: "video/VP8"}, "track-one", "stream-one",
	)
	require.NoError(t, err)

	_, err = pcAnswer.AddTrack(localTrack)
	require.NoError(t, err)

	onTrackFired, onTrackFiredFunc := context.WithCancel(context.Background())
	pcOffer.OnTrack(func(track *TrackRemote, r *RTPReceiver) {
		onTrackFiredFunc()
	})

	assert.NoError(t, signalPair(pcOffer, pcAnswer))

	sendVideoUntilDone(onTrackFired.Done(), t, []*TrackLocalStaticSample{localTrack})

	closePairNow(t, pcOffer, pcAnswer)
}

// Assert the following behaviors:
// - Offerer can add a recvonly transceiver
// - During negotiation, answerer peer adds an inactive (or sendonly) transceiver
// - Offerer can add a track
// - Answerer can receive the RTP packets.
func TestPeerConnection_Renegotiation_AddRecvonlyTransceiver_Then_Send(t *testing.T) {
	lim := test.TimeOut(time.Second * 30)
	defer lim.Stop()

	report := test.CheckRoutines(t)
	defer report()

	pcOffer, pcAnswer, err := newPair()
	if err != nil {
		t.Fatal(err)
	}

	_, err = pcOffer.AddTransceiverFromKind(
		RTPCodecTypeVideo,
		RtpTransceiverInit{
			Direction: RTPTransceiverDirectionRecvonly,
		},
	)
	assert.NoError(t, err)

	assert.NoError(t, signalPair(pcOffer, pcAnswer))

	localTrack, err := NewTrackLocalStaticSample(
		RTPCodecCapability{MimeType: "video/VP8"}, "track-one", "stream-one",
	)
	require.NoError(t, err)

	_, err = pcOffer.AddTrack(localTrack)
	require.NoError(t, err)

	onTrackFired, onTrackFiredFunc := context.WithCancel(context.Background())
	pcAnswer.OnTrack(func(track *TrackRemote, r *RTPReceiver) {
		onTrackFiredFunc()
	})

	assert.NoError(t, signalPair(pcOffer, pcAnswer))

	sendVideoUntilDone(onTrackFired.Done(), t, []*TrackLocalStaticSample{localTrack})

	closePairNow(t, pcOffer, pcAnswer)
}
```

```console
$ go test -run AddRecvonlyTransceiver_Then_Recv -v
=== RUN   TestPeerConnection_Renegotiation_AddRecvonlyTransceiver_Then_Recv
    peerconnection_renegotiation_test.go:96:
                Error Trace:    peerconnection_renegotiation_test.go:96
                Error:          Received unexpected error:
                                invalid state change in RTPTransceiver.setSending
                Test:           TestPeerConnection_Renegotiation_AddRecvonlyTransceiver_Then_Recv
^Csignal: interrupt
FAIL    github.com/pion/webrtc/v3       0.853s

$ go test -run AddRecvonlyTransceiver_Then_Send -v
=== RUN   TestPeerConnection_Renegotiation_AddRecvonlyTransceiver_Then_Send
pc ERROR: 2021/03/20 11:43:11 Incoming unhandled RTP ssrc(2668046615), OnTrack will not be fired. mid RTP Extensions required for Simulcast
^Csignal: interrupt
FAIL    github.com/pion/webrtc/v3       1.081s
```

### What did you expect?

I expected the `AddTrack` call to succeed, and both tests to pass.

### What happened?

I realized that this is caused by ae0f74edffc6bd5e020ebe9bf5fc80697888eb11 introduced by #1689. If I revert this commit, the test passes.

#### TestPeerConnection_Renegotiation_AddRecvonlyTransceiver_Then_Recv

After the negotiation, the `pcAnswer` already has a transceiver with `sendonly` direction, but it has no track.

The track added to the sender, but the check in `webrtc.RTPTransceiver.setSendingTrack` fails and errors out.

```go
	switch {
	case track != nil && t.Direction() == RTPTransceiverDirectionRecvonly:
		t.setDirection(RTPTransceiverDirectionSendrecv)
	case track != nil && t.Direction() == RTPTransceiverDirectionInactive:
		t.setDirection(RTPTransceiverDirectionSendonly)
	case track == nil && t.Direction() == RTPTransceiverDirectionSendrecv:
		t.setDirection(RTPTransceiverDirectionRecvonly)
	case track == nil && t.Direction() == RTPTransceiverDirectionSendonly:
		t.setDirection(RTPTransceiverDirectionInactive)
	default:
		return errRTPTransceiverSetSendingInvalidState
	}
```
Source: https://github.com/pion/webrtc/blob/v3.0.16/rtptransceiver.go#L121

#### TestPeerConnection_Renegotiation_AddRecvonlyTransceiver_Then_Send

In the final negotiation, the following is sent by the answerer:

```sdp
a=mid:0
...
a=ssrc:2668046615 cname:stream-one
a=ssrc:2668046615 msid:stream-one track-one
a=ssrc:2668046615 mslabel:stream-one
a=ssrc:2668046615 label:track-one
a=msid:stream-one track-one
a=sendrecv
```

but the answerer responds with:

```sdp
a=mid:0
...
a=sendonly
```

---

Reverting the mentioned commit fixes both tests:

```console
$ git revert ae0f74edffc6bd5e020ebe9bf5fc80697888eb11
[jeremija/issue-1722 d223265] Revert "Set answer as sendonly in case of a recvonly offer"
 3 files changed, 2 insertions(+), 135 deletions(-)

$ go test -run AddRecvonlyTransceiver_Then_Send -v
=== RUN   TestPeerConnection_Renegotiation_AddRecvonlyTransceiver_Then_Send
--- PASS: TestPeerConnection_Renegotiation_AddRecvonlyTransceiver_Then_Send (0.47s)
PASS
ok      github.com/pion/webrtc/v3       0.476s

$ go test -run AddRecvonlyTransceiver_Then_Recv -v
=== RUN   TestPeerConnection_Renegotiation_AddRecvonlyTransceiver_Then_Recv
--- PASS: TestPeerConnection_Renegotiation_AddRecvonlyTransceiver_Then_Recv (0.44s)
PASS
ok      github.com/pion/webrtc/v3       0.448s
```

### PR DESCRIPTION
**Pull request by jeremija**
Which were previously unable to:

1. have a sending track set to them, or
2. receive a track after renegotiation.

I'm not 100% sure if this covers all cases where a track is added and
removed and then added again. BUT IIRC there was a change that did not
allow transceiver reuse after a track was removed from it. Again, not
100% sure.

Fixes #1722.

### CODE REVIEW

**Comment by aler9** [comment]
Hello, regarding the specific issue, i can confirm that the patch fixes it and i'm sorry for the inconvenience.

 [i covered the cases](https://github.com/pion/webrtc/blob/ae0f74edffc6bd5e020ebe9bf5fc80697888eb11/peerconnection_go_test.go#L1232) in which the offerer creates a transceiver and the answerer creates a transceiver, while you're covering the more complex case in which the offerer creates a recvonly transceiver, the answerer doesn't, and therefore it creates an inactive, sendonly, transceiver; then a track is added.

I don't know if the transceiver should be turned into a sendrecv transceiver (like you do) or into a recvonly transceiver (there isn't enough documentation, i tried to change it to recvonly and tests passed anyway).

I don't know if it there are any more cases to cover in this specific scenario.

**Review by aler9 — DISMISSED** [review]

File: peerconnection_renegotiation_test.go [hunk 1]
```diff
@@ -60,6 +60,127 @@ func sdpMidHasSsrc(offer SessionDescription, mid string, ssrc SSRC) bool {
...
+			assert.NoError(t, signalPair(pcOffer, pcAnswer))
+
+			sendVideoUntilDone(onTrackFired.Done(), t, []*TrackLocalStaticSample{localTrack})
+
+			closePairNow(t, pcOffer, pcAnswer)
+		})
+	}
+}
+
+func TestPeerConnection_Renegotiation_AddRecvonlyTransceiver_Then_Send(t *testing.T) {
```
Comment (aler9) [inline peerconnection_renegotiation_test.go:142]: remove this, it was merged into the previous test

**Review by aler9 — CHANGES_REQUESTED** [review]

**Comment by jeremija** [comment]
> Hello, regarding the specific issue, i can confirm that the patch fixes it and i'm sorry for the inconvenience.

No worries, thanks you for a quick review!
 
> [i covered the cases](https://github.com/pion/webrtc/blob/ae0f74edffc6bd5e020ebe9bf5fc80697888eb11/peerconnection_go_test.go#L1232) in which the offerer creates a transceiver and the answerer creates a transceiver, while you're covering the more complex case in which the offerer creates a recvonly transceiver, the answerer doesn't, and therefore it creates an inactive, sendonly, transceiver; then a track is added.

Yeah I figured that most likely very few use this logic. I use `simple-peer` on the frontend which lets the server know to add a transceiver via a websocket message. The reason for this is that in Pion v2 you'd have to worry about `PayloadType`, and that was the only way to ensure that the tracks between browsers would be compatible.

Perhaps with Pion v3 a lot of it can be simplified, and I'll no longer have a need for this use case, but I'd prefer to do this gradually.

> I don't know if the transceiver should be turned into a sendrecv transceiver (like you do) or into a recvonly transceiver (there isn't enough documentation, i tried to change it to recvonly and tests passed anyway).
> 
> I don't know if it there are any more cases to cover in this specific scenario.

Are you referring to the case below I added in `SetRemoteDescription`?

```go
			case direction == RTPTransceiverDirectionSendrecv:
				if t.Direction() == RTPTransceiverDirectionSendonly {
					t.setDirection(RTPTransceiverDirectionSendrecv)
				}
			}
```

In the above case the transceiver `t` was already used for sending a track, changing it to `Recvonly` would interrupt the stream after a negotiation.

But I'm also not 100% sure if there are any more edge cases that we'd need to cover.

File: peerconnection_renegotiation_test.go (hunk 1 above)
Comment (jeremija) [reply peerconnection_renegotiation_test.go]: Thanks, done!

**Comment by Sean-Der** [comment]
Thank you so much for fixing @jeremija and reviewing @aler9 this makes my life so much easier!

File: peerconnection_renegotiation_test.go [hunk 2]
```diff
@@ -60,6 +60,85 @@ func sdpMidHasSsrc(offer SessionDescription, mid string, ssrc SSRC) bool {
...
+		answererSends bool
+	}
+
+	testCases := []testCase{
+		// Assert the following behaviors:
+		// - Offerer can add a recvonly transceiver
+		// - During negotiation, answerer peer adds an inactive (or sendonly) transceiver
+		// - Offerer can add a track
+		// - Answerer can receive the RTP packets.
+		{"add reconvly, then receive from answerer", false},
```
Comment (aler9) [inline peerconnection_renegotiation_test.go:75]: recvonly

**Review by aler9 — CHANGES_REQUESTED** [review]

File: peerconnection_renegotiation_test.go (hunk 2 above)
Comment (jeremija) [reply peerconnection_renegotiation_test.go]: Thanks, fixed!

**Review by aler9 — APPROVED** [review]
