### PR TITLE
[WIP] Fix datachannel not returning EOF

### LINKED ISSUE #652: EOF returns earlier than the last message on receipt of Reset
### Your environment.
  - Version: sctp e0c13 (webrtc@v2.0.10, sctp@v1.6.1)
  - Browser: n/a
 
### What did you do?
libp2p test (SubTestPingPong) is failing.
The test uses ioutil.ReadAll() in datachannel's detached mode which reads data until EOF is received. 
See slack thread for more details: https://gophers.slack.com/archives/CAK2124AG/p1556658527035200

### What did you expect?
When the sender side's SCTP stream is closed, Reset chunk will be received with indicating the last TSN in the chunk. Receiver side should forward all the data received that are equal to or smaller than the reset's TSN. 

### What happened?
stream.ReadSCTP() returns EOF before the last message (which has TSN <= the last TSN reset chunk indicates) becomes available to read.

### PR DESCRIPTION
**Pull request by enobufs**
This updates sctp and datachannel that fix EOF related issues.

> sctp and datachannel needs to be merged and tagged before we merge this. 

Fixes #652

### CODE REVIEW

File: datachannel_go_test.go [hunk 1]
```diff
@@ -345,3 +352,218 @@ func TestDataChannelBufferedAmount(t *testing.T) {
 		assert.True(t, nCbs > 0, "callback should be made at least once")
 	})
 }
+
+func TestEOF(t *testing.T) {
+	log := logging.NewDefaultLoggerFactory().NewLogger("test")
+	label := "test-channel"
+	testData := []byte("this is some test data")
+
+	checkError := func(t *testing.T, err error) {
```
Comment (albrow) [inline datachannel_go_test.go]: Are we trying to eventually remove the `stretchr/testify/assert` dependency? Because if not, you can use `assert.NoError(t, err)` instead of writing your own `checkError` function. It does the same thing.

File: datachannel_go_test.go [hunk 2]
```diff
@@ -345,3 +352,218 @@ func TestDataChannelBufferedAmount(t *testing.T) {
...
+			} else {
+				log.Debug("Received pong GOOD!")
+			}
+		}()
+
+		wg.Wait()
+	})
+
+	t.Run("No detach", func(t *testing.T) {
+		// streams := 1
```
Comment (albrow) [inline datachannel_go_test.go]: We should remove some of these outdated comments. `// streams := 1` and the comments about detached mode.

File: datachannel_go_test.go (hunk 1 above)
Comment (enobufs) [reply datachannel_go_test.go]: `assert.NoError(t, err)` is good.  will switch to that.

File: datachannel_go_test.go (hunk 2 above)
Comment (enobufs) [reply datachannel_go_test.go]: True. will remove it.

**Comment by backkem** [comment]
As mentioned in pion/datachannel#18 this now fails TestEOF/Detach. What are your thoughts @enobufs?

File: datachannel_go_test.go (hunk 1 above)
Comment (enobufs) [reply datachannel_go_test.go]: Done
