### PR TITLE
Move transceiver selection inside SetRemoteDescription and CreateOffer

### LINKED ISSUE #1171: Pion should create a recvonly transceiver when needed.
### Your environment.
  - Version: master currently @ 18dfe7919313be036ec632e47856903596f25722
  - Browser: *include version*
  - Other Information - *stacktraces, related issues, suggestions how to fix, links for us to have context*

### Issue Description

If a remote adds a new track that creates a new remote transceiver, when receiving the offer, pion in `setRemoteDescription` won't find any available recvonly transceiver and no receiver will be started. Later when we'll call `CreateAnswer`, `generateMatchedSDP` will create a new `inactive` transceiver and report it in the answer. The user so won't be notified of any new track (with `OnTrack` handler).

A browser like chrome/firefox instead behave differently and they'll create a recvonly transceiver and the new track will be available.

I think that's the reason why all the pion examples manually create some transceivers calling `AddTransceiver*`.
Additionally this way of calling `AddTransceiver*` could work for the first negotiation, but if the remote start removing and adding tracks, also if we add tons of transceiver with `AddTransceiver` they could be ignored by the remote that will add an additional transceiver.

The pion behavior looks against the spec that at the end of [4.4.1.5 Set the RTCSessionDescriptionSet](https://w3c.github.io/webrtc-pc/#set-the-rtcsessiondescription)  says:

```
If no suitable transceiver was found (transceiver is unset), run the following steps:

Create an RTCRtpSender, sender, from the media description using sendEncodings.

Create an RTCRtpReceiver, receiver, from the media description.

Create an RTCRtpTransceiver with sender, receiver and an RTCRtpTransceiverDirection value of "recvonly", and let transceiver be the result.

Add transceiver to the connection's set of transceivers.
```

### Proposed solution.

Refactor `setRemoteDescription` to parse the media sections (now this is only done later by `CreateAnswer`) and add missing `recvonly` transceivers. In this way the transceiver is available when `setRemoteDescription` will call startTransports/startRenegotiation that will start the related receivers.

### LINKED ISSUE #1178: Media section mids generated could conflict with recycled m= sections
### Your environment.
  - Version: master currently @ abe3ea1ea86d0daafca4a4f08c2ac6f36e5cddcf
  - Browser: not relevant

### Issue Description

Currently new media session mid generated by `generateMatchedSDP` are number with value set to just the length +1 of the remote current media descriptions.

JSEP defines the possibility to recycle a media description at a specific index. The spec says that it should have a new mid. 

```
    * If any RtpTransceiver has been added, and there exists an m=
      section with a zero port in the current local description or the
      current remote description, that m= section MUST be recycled by
      generating an m= section for the added RtpTransceiver as if the m=
      section were being added to the session description (including a
      new MID value), and placing it at the same index as the m= section
      with a zero port.
```

If also the remote generates mid as increasing numbers (like chrome and firefox do) the above logic could generate a mid conflicting with an existing one.

### PR DESCRIPTION
**Pull request by sgotti**
#### Description

This tries to better match the JSEP spec and will fix at least two
issues:  #1171 and #1178

* Move transceiver selection/creation in SetRemoteDescription and
CreateOffer
* In SetRemoteDescription also create new Transceivers of type recvonly
when no satisfying transceiver is available
* In CreateOffer generate unique mid in number format avoiding possible
collisions with remote provide mids and to also already handle a future
implementation of m= section rejection and reuse
* Now generateMatchedSDP will just find the transceivers with the
required mid since they are already selected previously.

More details in these extract from JSEP:

JSEP 5.10 (Applying a Remote Description) says:

```
For each m= section, the following steps MUST be performed

[...]

If the m= section is not associated with any RtpTransceiver
(possibly because it was dissociated in the previous step),
either find an RtpTransceiver or create one according to the
following steps:
```

JSEP 5.2 (Constructing an Offer) says:

```
[...]

An m= section is generated for each RtpTransceiver
that has been added to the PeerConnection, excluding any stopped
RtpTransceivers;
```

Note that we are currently directly associating a mid to a transceiver
in CreateOffer, instead the spec says to also keep a m= section index
mapping to a transceiver and set the transceiver mid only when applying
the local description. This is needed to support rollback of proposed
offer/answer but currently we don't have support and tests for rollback
situations.

#### Reference issue
Fixes #1171 
Fixes #1178

### CODE REVIEW

File: peerconnection.go [hunk 1]
```diff
@@ -732,16 +773,56 @@ func (pc *PeerConnection) SetRemoteDescription(desc SessionDescription) error {
...
+			t, localTransceivers = findByMid(midValue, localTransceivers)
+			if t == nil {
+				t, localTransceivers = satisfyTypeAndDirection(kind, direction, localTransceivers)
+			}
+			if t == nil {
+				receiver, err := pc.api.NewRTPReceiver(kind, pc.dtlsTransport)
+				if err != nil {
+					return err
+				}
+				t = pc.newRTPTransceiver(receiver, nil, RTPTransceiverDirectionRecvonly, kind)
```
Comment (jeremija) [inline peerconnection.go:811]: <strike>I'm not sure if we should be adding `recvonly` transceiver here. I believe the previous code used to add an `inactive` transceiver. Adding a `recvonly` transceiver means we will blindly accept any track that the remote client gives to us. </strike>

*edit*  JSEP spec [mandates that a transceiver is created with direction `recvonly`](https://tools.ietf.org/html/draft-ietf-rtcweb-jsep-25#section-5.10):

> ```
> 5.10.  Applying a Remote Description
> 
> [...]
> 
>    For each m= section, the following steps MUST be performed; if any
>    parameters are out of bounds, or cannot be applied, processing MUST
>    stop and an error MUST be returned.
> 
>    [...]
> 
>    o  If the m= section proto value indicates use of RTP:
> 
>       *  If the m= section is not associated with any RtpTransceiver
>          (possibly because it was dissociated in the previous step),
>          either find an RtpTransceiver or create one according to the
>          following steps:
> 
>          [...]
> 
>          +  If no RtpTransceiver was found in the previous step, create
>             one with a recvonly direction.```

Does this mean we'll no longer have to call `AddTransceiver` when the remote peer wants to send a track? 

I thought the browsers require `AddTransceiver` to be called on the offer-receiving peer as well :/

**Comment by sgotti** [comment]
@jeremija @Sean-Der If you think this makes sense, do you think we could remove from the examples the various `AddTransceiverCall` that are not needed anymore?

P.S. I'd like to continue on this to better follow jsep to handle rollbacks, media section reuse on transceiver.stop etc... Just wanted to make this in small steps.

File: peerconnection.go [hunk 2]
```diff
@@ -400,6 +407,41 @@ func (pc *PeerConnection) CreateOffer(options *OfferOptions) (SessionDescription
...
+				continue
+			}
+			pc.greaterMid++
+			err := t.setMid(strconv.Itoa(pc.greaterMid))
+			if err != nil {
+				return SessionDescription{}, err
+			}
+		}
+	}
+
```
Comment (jeremija) [inline peerconnection.go:444]: I think this should happen in `SetLocalDescription` and not in `CreateOffer`?

> ```
> 5.9.  Applying a Local Description
> 
>    [...]
> 
>    o  If the m= section proto value indicates use of RTP:
> 
>       *  If there is no RtpTransceiver associated with this m= section,
>          find one and associate it with this m= section according to the
>          following steps.  Note that this situation will only occur when
>          applying an offer.
> 
>          +  Find the RtpTransceiver that corresponds to this m= section,
>             using the mapping between transceivers and m= section
>             indices established when creating the offer.
> 
>          +  Set the value of this RtpTransceiver's mid property to the
>             MID of the m= section.
> ```

Comment (jeremija) [reply peerconnection.go:444]: @sgotti and I discussed this on Slack and decided to make this change in a later PR to keep this one simpler.

**Comment by jeremija** [comment]
> do you think we could remove from the examples the various `AddTransceiverCall` that are not needed anymore?

@sgotti This is what I'm not sure about. See [Unified plan transition guide](https://docs.google.com/document/d/1-ZfikoUtoJa9k-GZG1daN0BU3IjIanQ_JSscHxQesvU/edit#):

> In Plan B, the legacy createOffer()-constraints offerToReceiveAudio/offerToReceiveVideo would create m= sections for it to be possible to receive any number of tracks. In Unified Plan this constraint only works for a single track per kind as it only creates one audio and/or video transceiver; the spec advises using addTransceiver() instead. Chrome only partially supports this constraint; it works for offering but the createOffer()-transceiver is not immediately visible, leading to some unexpected behavior.

I'm aware that the JSEP RFC mandates to create `recvonly` transceivers for unmatched remote media sections for RTP streams. But why do the browsers seem to require calling `addTransceiver` before receiving more than one track?

**Comment by jeremija** [comment]
Even the [webrtc-pc](https://w3c.github.io/webrtc-pc/#set-the-rtcsessiondescription) mandates to create a transceiver with `recvonly` when not found:


> 4.5.9.2.5. If no suitable transceiver was found (transceiver is unset), run the following steps:
> 
>     1. Create an RTCRtpSender, sender, from the media description using sendEncodings.
> 
>     2. Create an RTCRtpReceiver, receiver, from the media description.
> 
>     3. Create an RTCRtpTransceiver with sender, receiver and an RTCRtpTransceiverDirection value of "recvonly", and let transceiver be the result.
> 
>     4. Add transceiver to the connection's set of transceivers.

Just trying to understand why we then need to call `addTransceiver` in browsers 😕

**Comment by sgotti** [comment]
@jeremija I never had the need to call AddTransceiver in chrome/firefox. I'll provide you an  example later if you want.

**Comment by jeremija** [comment]
@sgotti Were you creating offers from the side that was adding the tracks?

**Comment by sgotti** [comment]
> @sgotti Were you creating offers from the same peer that was adding the tracks?
> 
> **EDIT** I think that's it. The `AddTransceiver()` function needs to be called when we want to offer to receive tracks. But if another peer is creating the offer, the spec mandates the other peer receiving the remote offer to accept (all) the tracks the remote peer is offering. I was looking at it from the direction of the peer that's offering (to receive), but you added an `if !weOffer` check to `SetRemoteDescription`.
> 
> To sum up:
> 
> * if a local peer creates an offer, the remote peer might not be able to send all the tracks they want if there are not enough transceivers for all audio/video media sections, _but_
> * if a local peer receives a remote offer with audio/video media sections, it needs to create missing transceivers with direction `recvonly`. This was previously not the case in pion, and this PR fixes this.

Yeah. Just a small demo to test this: https://jsfiddle.net/sgotti/q3h2saL5/1/

**Comment by jeremija** [comment]
Thanks for the demo! Like I said in my last comment, I was looking at it from the wrong side. LGTM - feel free to merge when you are ready as far as I'm concerned! We can remove the unnecessary `AddTransceiver` calls later if you want to focus on the other PRs.

**Comment by sgotti** [comment]
@jeremija Thanks! Merging.

**Comment by longsleep** [comment]
@sgotti this breaks things for me. Preliminary check shows that the sdp created by pion sets the transceiver to `recvonly` where it really must be `sendonly` because pion is sending and not the other side.

**Comment by jeremija** [comment]
@longsleep Sorry to hear that - can you please provide an example?

**Comment by jeremija** [comment]
The only effective difference of this PR should be is that there's no longer a need to call `AddTransceiver` for incoming tracks on peers receiving the offer. See this test and my comment below:

```golang
func TestAddTrack_Direction(t *testing.T) {
	api := NewAPI()
	lim := test.TimeOut(time.Second * 30)
	defer lim.Stop()

	report := test.CheckRoutines(t)
	defer report()

	api.mediaEngine.RegisterDefaultCodecs()
	pcOffer, pcAnswer, err := api.newPair(Configuration{})
	assert.NoError(t, err)

	trOffer := pcOffer.GetTransceivers()
	assert.Equal(t, 0, len(trOffer))

	track, err := pcOffer.NewTrack(DefaultPayloadTypeVP8, rand.Uint32(), "foo", "bar")
	assert.NoError(t, err)
	_, err = pcOffer.AddTrack(track)
	assert.NoError(t, err)

	trOffer = pcOffer.GetTransceivers()
	assert.Equal(t, 1, len(trOffer))
	assert.Equal(t, RTPTransceiverDirectionSendrecv.String(), trOffer[0].Direction().String())

	err = signalPair(pcOffer, pcAnswer)
	assert.NoError(t, err)

	trOffer = pcOffer.GetTransceivers()
	trAnswer := pcAnswer.GetTransceivers()

	assert.Equal(t, 1, len(trOffer))
	assert.Equal(t, RTPTransceiverDirectionSendrecv.String(), trOffer[0].Direction().String())
	assert.Equal(t, 1, len(trAnswer))
        //
        // previous to this PR, the direction would've been "inactive"
        // but now it's "recvonly"
        //
	assert.Equal(t, RTPTransceiverDirectionRecvonly.String(), trAnswer[0].Direction().String())

	assert.NoError(t, pcOffer.Close())
	assert.NoError(t, pcAnswer.Close())
}
```

**Comment by longsleep** [comment]
The scenario is as follows, pion sends a track while the other end sends none and pion is not the offer. Wih this patch, the SDP generated by pion has an `a=recvonly` line for the track it sends (which never makes sense imo), while without this patch, it is rightfully `a=sendonly`.

Remains to say that both sides initially start without any track, and eventually pion side adds the track (requesting renegotiation from the initiator first).

So goes like this.
1. other side create offer (data channel only)
2. pion side creates answer for received offer (data channel only, sendrecv)
3. connection state changes to connected on both sides
4. pion adds track
5. pion signaling requests other side to add a transceiver for added track
6. other side adds transceiver, creates new offer (renegotiation, offer contains media for requested type with recvonly)
7. pion side creates answer for received offer (data channel and media), this answer now contains the media previously added by pion, but the direction in the answer is recvonly while it must be sendonly
8. other side does not receive the track (it receives the data though, but the remote sdp sends data while the media for it is recvonly = gets ignored).

**Comment by longsleep** [comment]
Dump of the SDPs as described in the flow before

```
type: offer, sdp: v=0
o=- 2158105433681526427 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0
a=msid-semantic: WMS
m=application 9 UDP/DTLS/SCTP webrtc-datachannel
c=IN IP4 0.0.0.0
a=ice-ufrag:2uLl
a=ice-pwd:mWQ4CpfJyqZ9XFO4Pbilf9oI
a=ice-options:trickle
a=fingerprint:sha-256 63:D7:DB:07:3F:0D:29:13:74:DE:8B:EA:7F:CC:69:84:6A:52:4E:B1:01:7D:3F:68:AE:17:BB:90:10:6C:EE:BB
a=setup:actpass
a=mid:0
a=sctp-port:5000
a=max-message-size:262144
```
```
type: answer, sdp: v=0
o=- 514202162 1588685341 IN IP4 0.0.0.0
s=-
t=0 0
a=fingerprint:sha-256 F1:BD:EF:C5:F0:54:9F:6B:8F:7C:18:9C:E7:AD:56:78:19:79:D6:6A:92:B7:CB:E1:A2:0F:CC:E3:E1:2C:53:A1
a=ice-lite:ice-lite
a=group:BUNDLE 0
m=application 9 DTLS/SCTP 5000
c=IN IP4 0.0.0.0
a=setup:passive
a=mid:0
a=sendrecv
a=sctpmap:5000 webrtc-datachannel 1024
a=ice-ufrag:ySGFhHajSpbrENVZ
a=ice-pwd:itNtfzKBMKZYVkJccsOjJRjyOLNjIjCN
a=candidate:foundation 1 udp 2130706431 192.168.1.164 38743 typ host generation 0
a=candidate:foundation 2 udp 2130706431 192.168.1.164 38743 typ host generation 0
a=end-of-candidates
```

```
type: offer, sdp: v=0
o=- 2158105433681526427 3 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 1
a=msid-semantic: WMS
m=application 45005 UDP/DTLS/SCTP webrtc-datachannel
c=IN IP4 77.189.130.32
a=candidate:2085243720 1 udp 2122260223 192.168.1.70 45005 typ host generation 0 network-id 1 network-cost 10
a=candidate:2321167004 1 udp 1686052607 77.189.130.32 45005 typ srflx raddr 192.168.1.70 rport 45005 generation 0 network-id 1 network-cost 10
a=ice-ufrag:2uLl
a=ice-pwd:mWQ4CpfJyqZ9XFO4Pbilf9oI
a=ice-options:trickle
a=fingerprint:sha-256 63:D7:DB:07:3F:0D:29:13:74:DE:8B:EA:7F:CC:69:84:6A:52:4E:B1:01:7D:3F:68:AE:17:BB:90:10:6C:EE:BB
a=setup:actpass
a=mid:0
a=sctp-port:5000
a=max-message-size:262144
m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 102 122 127 121 125 107 108 109 124 120 123
c=IN IP4 0.0.0.0
b=AS:1000
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:2uLl
a=ice-pwd:mWQ4CpfJyqZ9XFO4Pbilf9oI
a=ice-options:trickle
a=fingerprint:sha-256 63:D7:DB:07:3F:0D:29:13:74:DE:8B:EA:7F:CC:69:84:6A:52:4E:B1:01:7D:3F:68:AE:17:BB:90:10:6C:EE:BB
a=setup:actpass
a=mid:1
a=extmap:14 urn:ietf:params:rtp-hdrext:toffset
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:13 urn:3gpp:video-orientation
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:12 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:11 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=extmap:8 http://tools.ietf.org/html/draft-ietf-avtext-framemarking-07
a=extmap:9 http://www.webrtc.org/experiments/rtp-hdrext/color-space
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:5 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:6 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=recvonly
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:98 VP9/90000
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=fmtp:98 profile-id=0
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=98
a=rtpmap:100 VP9/90000
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=fmtp:100 profile-id=2
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=rtpmap:102 H264/90000
a=rtcp-fb:102 goog-remb
a=rtcp-fb:102 transport-cc
a=rtcp-fb:102 ccm fir
a=rtcp-fb:102 nack
a=rtcp-fb:102 nack pli
a=fmtp:102 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f
a=rtpmap:122 rtx/90000
a=fmtp:122 apt=102
a=rtpmap:127 H264/90000
a=rtcp-fb:127 goog-remb
a=rtcp-fb:127 transport-cc
a=rtcp-fb:127 ccm fir
a=rtcp-fb:127 nack
a=rtcp-fb:127 nack pli
a=fmtp:127 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42001f
a=rtpmap:121 rtx/90000
a=fmtp:121 apt=127
a=rtpmap:125 H264/90000
a=rtcp-fb:125 goog-remb
a=rtcp-fb:125 transport-cc
a=rtcp-fb:125 ccm fir
a=rtcp-fb:125 nack
a=rtcp-fb:125 nack pli
a=fmtp:125 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtpmap:107 rtx/90000
a=fmtp:107 apt=125
a=rtpmap:108 H264/90000
a=rtcp-fb:108 goog-remb
a=rtcp-fb:108 transport-cc
a=rtcp-fb:108 ccm fir
a=rtcp-fb:108 nack
a=rtcp-fb:108 nack pli
a=fmtp:108 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42e01f
a=rtpmap:109 rtx/90000
a=fmtp:109 apt=108
a=rtpmap:124 red/90000
a=rtpmap:120 rtx/90000
a=fmtp:120 apt=124
a=rtpmap:123 ulpfec/90000
```

```
type: answer, sdp: v=0
o=- 276235157 1588685360 IN IP4 0.0.0.0
s=-
t=0 0
a=fingerprint:sha-256 F1:BD:EF:C5:F0:54:9F:6B:8F:7C:18:9C:E7:AD:56:78:19:79:D6:6A:92:B7:CB:E1:A2:0F:CC:E3:E1:2C:53:A1
a=ice-lite:ice-lite
a=group:BUNDLE 0 1
m=application 9 DTLS/SCTP 5000
c=IN IP4 0.0.0.0
a=setup:passive
a=mid:0
a=sendrecv
a=sctpmap:5000 webrtc-datachannel 1024
a=ice-ufrag:ySGFhHajSpbrENVZ
a=ice-pwd:itNtfzKBMKZYVkJccsOjJRjyOLNjIjCN
a=candidate:foundation 1 udp 2130706431 192.168.1.164 38743 typ host generation 0
a=candidate:foundation 2 udp 2130706431 192.168.1.164 38743 typ host generation 0
a=end-of-candidates
m=video 9 UDP/TLS/RTP/SAVPF 96 98 100 102 127 125 108
c=IN IP4 0.0.0.0
b=AS:1000
a=setup:passive
a=mid:1
a=ice-ufrag:ySGFhHajSpbrENVZ
a=ice-pwd:itNtfzKBMKZYVkJccsOjJRjyOLNjIjCN
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 goog-remb 
a=rtcp-fb:96 ccm 
a=rtcp-fb:96 nack 
a=rtcp-fb:96 nack pli 
a=rtpmap:98 VP9/90000
a=fmtp:98 profile-id=0
a=rtcp-fb:98 goog-remb 
a=rtcp-fb:98 ccm 
a=rtcp-fb:98 nack 
a=rtcp-fb:98 nack pli 
a=rtpmap:100 VP9/90000
a=fmtp:100 profile-id=2
a=rtcp-fb:100 goog-remb 
a=rtcp-fb:100 ccm 
a=rtcp-fb:100 nack 
a=rtcp-fb:100 nack pli 
a=rtpmap:102 H264/90000
a=fmtp:102 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f
a=rtcp-fb:102 goog-remb 
a=rtcp-fb:102 ccm 
a=rtcp-fb:102 nack 
a=rtcp-fb:102 nack pli 
a=rtpmap:127 H264/90000
a=fmtp:127 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42001f
a=rtcp-fb:127 goog-remb 
a=rtcp-fb:127 ccm 
a=rtcp-fb:127 nack 
a=rtcp-fb:127 nack pli 
a=rtpmap:125 H264/90000
a=fmtp:125 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtcp-fb:125 goog-remb 
a=rtcp-fb:125 ccm 
a=rtcp-fb:125 nack 
a=rtcp-fb:125 nack pli 
a=rtpmap:108 H264/90000
a=fmtp:108 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42e01f
a=rtcp-fb:108 goog-remb 
a=rtcp-fb:108 ccm 
a=rtcp-fb:108 nack 
a=rtcp-fb:108 nack pli 
a=recvonly
a=candidate:foundation 1 udp 2130706431 192.168.1.164 38743 typ host generation 0
a=candidate:foundation 2 udp 2130706431 192.168.1.164 38743 typ host generation 0
a=end-of-candidates
```

answers are Pion, Offers is Google Chrome.

**Comment by longsleep** [comment]
For sake of completion, this is how the final pion sdp looks when it works (0b5e452)
```
type: answer, sdp: v=0
o=- 16460767 1588686484 IN IP4 0.0.0.0
s=-
t=0 0
a=fingerprint:sha-256 B5:06:CC:BC:58:31:0C:CA:8F:0C:7C:96:43:56:E4:89:6B:78:68:21:11:F9:24:BB:2A:A3:8C:6F:95:7A:9B:56
a=ice-lite:ice-lite
a=group:BUNDLE 0 1
m=application 9 DTLS/SCTP 5000
c=IN IP4 0.0.0.0
a=setup:passive
a=mid:0
a=sendrecv
a=sctpmap:5000 webrtc-datachannel 1024
a=ice-ufrag:dwUrknMKmkmtflad
a=ice-pwd:FKJeRJsfSjASXfBOphOKJKAPyjFkQDHE
a=candidate:foundation 1 udp 2130706431 192.168.1.164 38743 typ host generation 0
a=candidate:foundation 2 udp 2130706431 192.168.1.164 38743 typ host generation 0
a=end-of-candidates
m=video 9 UDP/TLS/RTP/SAVPF 96 98 100 102 127 125 108
c=IN IP4 0.0.0.0
b=AS:1000
a=setup:passive
a=mid:1
a=ice-ufrag:dwUrknMKmkmtflad
a=ice-pwd:FKJeRJsfSjASXfBOphOKJKAPyjFkQDHE
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 goog-remb 
a=rtcp-fb:96 ccm 
a=rtcp-fb:96 nack 
a=rtcp-fb:96 nack pli 
a=rtpmap:98 VP9/90000
a=fmtp:98 profile-id=0
a=rtcp-fb:98 goog-remb 
a=rtcp-fb:98 ccm 
a=rtcp-fb:98 nack 
a=rtcp-fb:98 nack pli 
a=rtpmap:100 VP9/90000
a=fmtp:100 profile-id=2
a=rtcp-fb:100 goog-remb 
a=rtcp-fb:100 ccm 
a=rtcp-fb:100 nack 
a=rtcp-fb:100 nack pli 
a=rtpmap:102 H264/90000
a=fmtp:102 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f
a=rtcp-fb:102 goog-remb 
a=rtcp-fb:102 ccm 
a=rtcp-fb:102 nack 
a=rtcp-fb:102 nack pli 
a=rtpmap:127 H264/90000
a=fmtp:127 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42001f
a=rtcp-fb:127 goog-remb 
a=rtcp-fb:127 ccm 
a=rtcp-fb:127 nack 
a=rtcp-fb:127 nack pli 
a=rtpmap:125 H264/90000
a=fmtp:125 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtcp-fb:125 goog-remb 
a=rtcp-fb:125 ccm 
a=rtcp-fb:125 nack 
a=rtcp-fb:125 nack pli 
a=rtpmap:108 H264/90000
a=fmtp:108 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42e01f
a=rtcp-fb:108 goog-remb 
a=rtcp-fb:108 ccm 
a=rtcp-fb:108 nack 
a=rtcp-fb:108 nack pli 
a=ssrc:2460579269 cname:stream_user1
a=ssrc:2460579269 msid:stream_user1 12aa1b1f-90c5-44e4-acfb-f7d903f90ba8
a=ssrc:2460579269 mslabel:stream_user1
a=ssrc:2460579269 label:12aa1b1f-90c5-44e4-acfb-f7d903f90ba8
a=msid:stream_user1 12aa1b1f-90c5-44e4-acfb-f7d903f90ba8
a=sendonly
a=candidate:foundation 1 udp 2130706431 192.168.1.164 38743 typ host generation 0
a=candidate:foundation 2 udp 2130706431 192.168.1.164 38743 typ host generation 0
a=end-of-candidates
```

**Comment by longsleep** [comment]
Looking at this more closely, it appars that the ssrc lines are missing when using this patch, so the recvonly might just be a side effect since pion does not have anything to sent. How this can be caused by this PR remains to be discovered.

**Comment by jeremija** [comment]
@longsleep Do you have any other transceivers added to your pion peer connection?

I wrote a test using your second SDP from Chrome to see what happens, but I get the correct `sendonly` direction.

```golang
func Test_failedsdp(t *testing.T) {
	sdp := `<-- your chrome sdp -->
`
	var remote SessionDescription
	remote.Type = SDPTypeOffer
	remote.SDP = sdp

	api := NewAPI()
	lim := test.TimeOut(time.Second * 30)
	defer lim.Stop()

	report := test.CheckRoutines(t)
	defer report()

	api.mediaEngine.RegisterDefaultCodecs()
	pc, err := api.NewPeerConnection(Configuration{})
	assert.NoError(t, err)

	// ANSWERER SENDS TRACK
	track, err := pc.NewTrack(DefaultPayloadTypeVP8, rand.Uint32(), "foo", "bar")
	assert.NoError(t, err)
	// _, err = pc.AddTrack(track)
	_, err = pc.AddTransceiverFromTrack(track, RtpTransceiverInit{Direction: RTPTransceiverDirectionSendonly})
	assert.NoError(t, err)

	err = pc.SetRemoteDescription(remote)
	assert.NoError(t, err)
	answer, err := pc.CreateAnswer(nil)
	assert.NoError(t, err)

	tr := pc.GetTransceivers()
	assert.Equal(t, 1, len(tr))
	assert.Equal(t, RTPTransceiverDirectionSendonly.String(), tr[0].Direction().String())
	t.Log("answer", answer.SDP)

	assert.NoError(t, pc.Close())
}
```

```
$ go test  ./ -run failedsdp
ok      github.com/pion/webrtc/v2       0.675s
```

**Comment by longsleep** [comment]
> @longsleep Do you have any other transceivers added to your pion peer connection?

@jeremija it indeed seems to be because of the behavior change "no longer a need to call AddTransceiver for incoming tracks on peers receiving the offer".

I was doing `pc.AddTransceiverFromTrack(track, transceiverInit)` to add a track on Pion peer connection. Changing that to `pc.AddTrack(track)` fixes the issue.

I will do further checks if that is indeed always working. Since before the transceiverInit took care to ensure to use a sendonly transceiver like this

```
transceiverInit := webrtc.RtpTransceiverInit{
		Direction: webrtc.RTPTransceiverDirectionSendonly,
	}
```

where it with AddTrack finds one of the existing transceivers.

So i guess the behavior change is intentional. I will open up another issue if i find that calling AddTrack instead does cause other issues.

**Comment by jeremija** [comment]
Yeah, the spec mandates new transceivers to be added using `recvonly` on the passive (offer-receiving) side, and pion did not used to follow this. Glad to hear you found a solution, please let us know if you find another issue @longsleep!

**Comment by longsleep** [comment]
@jeremija now that pion basically handles selection / creation of transceivers itself i run into the problem that when pion receives an offer with an `inactive` or `sendonly` transceiver in the remote offer pion still sends media to this transceiver and in the answer. Not sure what is the desired way to tell pion that the remote offer does not wish to receive a certain media.

**Comment by jeremija** [comment]
@longsleep if you wish to reject a track, you can call `rtpReceiver.Stop()`, which you'll receive in the `PeerConnection.OnTrack(f func(*webrtc.Track, *webrtc.RTPReceiver))` callback.

**Comment by longsleep** [comment]
> if you wish to reject a track, you can call `rtpReceiver.Stop()`

Well yes, but this is pion side. It is the other end (which is also the offerer) which in some cases might not wish to receive a certain media. Means the remote end has a receiver added for video which is inactive. This is received by Pion, but pion uses the inactive transceiver just fine. Do you mean the remote end should call Stop on its receiver once it receives an undesired track?

**Comment by sgotti** [comment]
@longsleep Sorry if I jump in, but I'd like to understand the issue: This patch just adds the ability to automatically create a recvonly transceiver when the incoming offer adds a new media track and there're no avialable transceiver on the answerer side. Everything else shouldn't have been changed. i.e you should be able to manually add new transceivers (with `AddTransceiverFromKind` ) that will be available to satisfy an incoming answer or for providing a new offer (using `AddTrack` or `AddTransceiverFromTrack`). If something has changed can you please open a new issue providing a reproducer?

> Means the remote end has a receiver added for video which is inactive. This is received by Pion, but pion uses the inactive transceiver just fine.

I'm not sure I understand what you're describing. If pion is receiving an offer it will only answer to the offer without offering something new in the answer. Can you provide a simple test case reproducer?

**Comment by longsleep** [comment]
@sgotti @jeremija thanks for your feedback. It made me think that i must do something wrong and indeed i was overthinking it. The solution is simply not to add a transceiver on the offering side if that side does not wish to receive a certain media. That solves the problem nicely. I will open a new issue if i should discover that more changes are required and feel that it needs discussion. Thanks again and sorry for the spam on this PR.
