### PR TITLE
Fix race issue caused by multiple gathering

### LINKED ISSUE #707: Gather() causing a race condition
Too many consecutive calls to `iceGatherer.Gather()` are causing a race condition because `pion/ice` operates asynchronously.

https://github.com/pion/webrtc/blob/master/peerconnection.go#L413
https://github.com/pion/webrtc/blob/master/peerconnection.go#L592
https://github.com/pion/webrtc/blob/master/peerconnection.go#L840
https://github.com/pion/webrtc/blob/master/peerconnection.go#L864

### PR DESCRIPTION
**Pull request by trivigy**
resolves #707

### CODE REVIEW

File: internal/ice/gatherer.go [hunk 1]
```diff
@@ -68,7 +68,7 @@ func NewGatherer(
 		}
 	}
 
-	candidateTypes := []ice.CandidateType{}
+	candidateTypes := make([]ice.CandidateType, 0)
```
Comment (trivigy) [inline internal/ice/gatherer.go]: This change has to do with Jetbrain's Goland go linting complaining that this is better.

File: peerconnection.go [hunk 2]
```diff
@@ -429,8 +428,8 @@ func (pc *PeerConnection) CreateOffer(options *OfferOptions) (SessionDescription
 	}
 
 	if pc.configuration.SDPSemantics == SDPSemanticsPlanB {
-		video := []*RTPTransceiver{}
-		audio := []*RTPTransceiver{}
+		video := make([]*RTPTransceiver, 0)
```
Comment (trivigy) [inline peerconnection.go]: Same issue as above regarding jetbrain goland linting.

File: peerconnection.go [hunk 3]
```diff
@@ -475,14 +474,14 @@ func (pc *PeerConnection) CreateOffer(options *OfferOptions) (SessionDescription
 		m.WithPropertyAttribute("setup:actpass")
 	}
 
-	sdp, err := d.Marshal()
```
Comment (trivigy) [inline peerconnection.go]: `sdp` conflicted with the pkg `sdp`
