### PR TITLE
Fix: Flakey OnNegotiationNeeded tests

### LINKED ISSUE #1401: Fix Flakey test TestNegotiationNeededRemoveTrack
```
=== RUN   TestNegotiationNeededRemoveTrack
    TestNegotiationNeededRemoveTrack: peerconnection_renegotiation_test.go:866:
                Error Trace:    peerconnection_renegotiation_test.go:866
                                                        peerconnection.go:317
                                                        operations.go:84
                                                        asm_amd64.s:1373
                Error:          Received unexpected error:
                                InvalidStateError: connection closed
                Test:           TestNegotiationNeededRemoveTrack
    TestNegotiationNeededRemoveTrack: peerconnection_renegotiation_test.go:869:
                Error Trace:    peerconnection_renegotiation_test.go:869
                                                        peerconnection.go:317
                                                        operations.go:84
                                                        asm_amd64.s:1373
                Error:          Received unexpected error:
                                InvalidStateError: connection closed
                Test:           TestNegotiationNeededRemoveTrack
    TestNegotiationNeededRemoveTrack: peerconnection_renegotiation_test.go:872:
                Error Trace:    peerconnection_renegotiation_test.go:872
                                                        peerconnection.go:317
                                                        operations.go:84
                                                        asm_amd64.s:1373
                Error:          Received unexpected error:
                                InvalidStateError: connection closed
                Test:           TestNegotiationNeededRemoveTrack
    TestNegotiationNeededRemoveTrack: peerconnection_renegotiation_test.go:875:
                Error Trace:    peerconnection_renegotiation_test.go:875
                                                        peerconnection.go:317
                                                        operations.go:84
                                                        asm_amd64.s:1373
                Error:          Received unexpected error:
                                InvalidStateError: connection closed
                Test:           TestNegotiationNeededRemoveTrack
    TestNegotiationNeededRemoveTrack: peerconnection_renegotiation_test.go:878:
                Error Trace:    peerconnection_renegotiation_test.go:878
                                                        peerconnection.go:317
                                                        operations.go:84
                                                        asm_amd64.s:1373
                Error:          Received unexpected error:
                                InvalidStateError: connection closed
                Test:           TestNegotiationNeededRemoveTrack
    TestNegotiationNeededRemoveTrack: peerconnection_renegotiation_test.go:881:
                Error Trace:    peerconnection_renegotiation_test.go:881
                                                        peerconnection.go:317
                                                        operations.go:84
                                                        asm_amd64.s:1373
                Error:          Received unexpected error:
                                InvalidStateError: connection closed
                Test:           TestNegotiationNeededRemoveTrack
panic: sync: negative WaitGroup counter
```

### PR DESCRIPTION
**Pull request by tarrencev**
Ensures negotiation needed handlers complete execution before closing peer connection.

Resolves #1401

### CODE REVIEW

File: peerconnection.go [hunk 1]
```diff
@@ -48,7 +48,7 @@ type PeerConnection struct {
 	idpLoginURL *string
 
 	isClosed               *atomicBool
-	negotiationNeeded      bool
+	isNegotiationNeeded    *atomicBool
```
Comment (Sean-Der) [inline peerconnection.go:51]: :fire:

**Review by Sean-Der — APPROVED** [review]
