### PR TITLE
Fix hanging test Transceiver_Mid

### LINKED ISSUE #1186: Transceiver Mid test failing
### Your environment.
  - Version: 4f362ee

### Steps to reproduce

```
$ go test ./ -run Transceiver_Mid -v -race -count=10
```

### Log

```
=== RUN   TestPeerConnection_Transceiver_Mid
==================
WARNING: DATA RACE
Read at 0x00c00037c410 by goroutine 70:
  github.com/pion/webrtc/v2.(*PeerConnection).startRTPSenders()
      /pion/webrtc/peerconnection.go:973 +0x149
  github.com/pion/webrtc/v2.(*PeerConnection).startRenegotation.func1()
      /pion/webrtc/peerconnection.go:1724 +0x9bc

Previous write at 0x00c00037c410 by goroutine 102:
  github.com/pion/webrtc/v2.(*RTPTransceiver).setSendingTrack()
      /pion/webrtc/rtptransceiver.go:96 +0x7a
  github.com/pion/webrtc/v2.(*PeerConnection).AddTrack()
      /pion/webrtc/peerconnection.go:1196 +0x20c
  github.com/pion/webrtc/v2.TestPeerConnection_Transceiver_Mid()
      /pion/webrtc/peerconnection_renegotation_test.go:297 +0xfa5
  testing.tRunner()
      /usr/local/go/1.14/libexec/src/testing/testing.go:992 +0x1eb

Goroutine 70 (running) created at:
  github.com/pion/webrtc/v2.(*PeerConnection).startRenegotation()
      /pion/webrtc/peerconnection.go:1691 +0x7e
  github.com/pion/webrtc/v2.(*PeerConnection).SetRemoteDescription()
      /pion/webrtc/peerconnection.go:822 +0xb6b
  github.com/pion/webrtc/v2.TestPeerConnection_Transceiver_Mid()
      /pion/webrtc/peerconnection_renegotation_test.go:292 +0xe66
  testing.tRunner()
      /usr/local/go/1.14/libexec/src/testing/testing.go:992 +0x1eb

Goroutine 102 (running) created at:
  testing.(*T).Run()
      /usr/local/go/1.14/libexec/src/testing/testing.go:1043 +0x660
  testing.runTests.func1()
      /usr/local/go/1.14/libexec/src/testing/testing.go:1285 +0xa6
  testing.tRunner()
      /usr/local/go/1.14/libexec/src/testing/testing.go:992 +0x1eb
  testing.runTests()
      /usr/local/go/1.14/libexec/src/testing/testing.go:1283 +0x527
  testing.(*M).Run()
      /usr/local/go/1.14/libexec/src/testing/testing.go:1200 +0x2ff
  main.main()
      _testmain.go:338 +0x223
==================
    TestPeerConnection_Transceiver_Mid: testing.go:906: race detected during execution of test
--- FAIL: TestPeerConnection_Transceiver_Mid (0.43s)
    : testing.go:906: race detected during execution of test
```

### PR DESCRIPTION
**Pull request by jeremija**
#### Reference issue
Fixes #1186

### CODE REVIEW

File: peerconnection_media_test.go [hunk 1]
```diff
@@ -1159,10 +1158,7 @@ func TestPeerConnection_Start_Right_Receiver(t *testing.T) {
 
 	assert.NoError(t, signalPair(pcOffer, pcAnswer))
 
-	pcOffer.negotiationLock.Lock()
-	pcAnswer.negotiationLock.Lock()
-	pcOffer.negotiationLock.Unlock()
-	pcAnswer.negotiationLock.Unlock()
```
Comment (sgotti) [inline peerconnection_media_test.go:1165]: @jeremija I did this trick of mixing the calls to avoid the linter `empty critical section` error. There should be a better way to fix this.

Comment (jeremija) [reply peerconnection_media_test.go:1165]: @sgotti thanks - I just disabled the linter for that line using `//nolint`:

```
func waitForNegotiation(pcs ...*PeerConnection) {
	for _, pc := range pcs {
		pc.negotiationLock.Lock()
		pc.negotiationLock.Unlock() //nolint
	}
}
```

**Comment by sgotti** [comment]
@jeremija LGTM!

**Comment by jeremija** [comment]
Thanks for your review @sgotti!
