### PR TITLE
Fixes DataChannel panic on sctp transport race

### LINKED ISSUE #1730: DataChannel crash in master test
```
panic: runtime error: invalid memory address or nil pointer dereference

[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x798be4]



goroutine 2211 [running]:

github.com/pion/sctp.(*Association).OpenStream(0x0, 0x3500000001, 0x0, 0x0, 0x0)
	/home/runner/go/pkg/mod/github.com/pion/sctp@v1.7.12/association.go:1300 +0x64
github.com/pion/datachannel.Dial(0x0, 0x1, 0xc0002abc68, 0x0, 0x0, 0x43978f)
	/home/runner/go/pkg/mod/github.com/pion/datachannel@v1.4.21/datachannel.go:73 +0x4f
github.com/pion/webrtc/v3.(*DataChannel).open(0xc00035a000, 0xc0001bc1e0, 0x1c, 0xc0000f6048)
	/home/runner/work/webrtc/webrtc/datachannel.go:164 +0x427
github.com/pion/webrtc/v3.(*PeerConnection).startSCTP(0xc00026e380)
	/home/runner/work/webrtc/webrtc/peerconnection.go:1323 +0x285
github.com/pion/webrtc/v3.(*PeerConnection).startRTP(0xc00026e380, 0x0, 0xc00000f1c0, 0xc000010528, 0x1, 0x1)
	/home/runner/work/webrtc/webrtc/peerconnection.go:2121 +0x9e5
github.com/pion/webrtc/v3.(*PeerConnection).SetRemoteDescription.func2()
	/home/runner/work/webrtc/webrtc/peerconnection.go:1149 +0x22c
github.com/pion/webrtc/v3.(*operations).start(0xc000200030)
	/home/runner/work/webrtc/webrtc/operations.go:84 +0xd5
created by github.com/pion/webrtc/v3.(*operations).Enqueue
	/home/runner/work/webrtc/webrtc/operations.go:35 +0x1ec
exit status 2
FAIL	github.com/pion/webrtc/v3	17.231s
FAIL
exit status 1
```

### PR DESCRIPTION
**Pull request by zyxar**
#### Description
`DataChannel.open` would panic during which if `PeerConnection` is closed,
stopping underlying `SCTPTransport` which sets association to `nil`;

`DataChannel.ensureSCTP` method doesn't guarantee `SCTPTransport`'s availability out of it's own scope.

Also fix similar issue in `SCTPTransport.Start`.

#### Reference issue
Fixes #1730

### CODE REVIEW

**Review by Sean-Der — APPROVED** [review]

**Comment by Sean-Der** [comment]
Thank you so much for taking this on :)

File: datachannel.go [hunk 1]
```diff
@@ -104,19 +104,22 @@ func (api *API) newDataChannel(params *DataChannelParameters, log logging.Levele
 
 // open opens the datachannel over the sctp transport
 func (d *DataChannel) open(sctpTransport *SCTPTransport) error {
+	if sctpTransport == nil {
+		return errSCTPNotEstablished
+	}
+	sctpTransport.lock.RLock()
```
Comment (Sean-Der) [inline datachannel.go:110]: @zyxar In a follow up commit `getAssocation` might be nice.  Wouldn't change the behavior of the code, but just nice to not use private members of other structs if we don't have too.

I have also thought about trying to move more stuff to internal. Will force us to write better code
