### PR TITLE
Assert SDPType in setDescription

### LINKED ISSUE #1297: SetRemoteDescription should return an error if SDPType is not set
Currently we silently fail to process if unset

### PR DESCRIPTION
**Pull request by Sean-Der**
Before users could pass a SessionDescription with a 0 type. This would
be discarded silently. Now we return an error that matches browser
behavior.

Resolves #1297

### CODE REVIEW

**Comment by cryptix** [comment]
LGTM!

File: peerconnection.go [hunk 1]
```diff
@@ -592,8 +592,11 @@ func (pc *PeerConnection) CreateAnswer(options *AnswerOptions) (SessionDescripti
 
 // 4.4.1.6 Set the SessionDescription
 func (pc *PeerConnection) setDescription(sd *SessionDescription, op stateChangeOp) error {
-	if pc.isClosed.get() {
+	switch {
+	case pc.isClosed.get():
 		return &rtcerr.InvalidStateError{Err: ErrConnectionClosed}
+	case sd.Type.String() == ErrUnknownType.Error():
```
Comment (at-wat) [inline peerconnection.go:598]:
```suggestion
	case newSDPType(sd.Type.String()) == SDPType(Unknown):
```
might be little bit better at semantics

File: peerconnection.go [hunk 2]
```diff
@@ -592,8 +592,11 @@ func (pc *PeerConnection) CreateAnswer(options *AnswerOptions) (SessionDescripti
...
+		return &rtcerr.TypeError{Err: fmt.Errorf("The provided value '%d' is not a valid enum value of type SDPType", sd.Type)}
```
Comment (at-wat) [inline peerconnection.go:599]: stylecheck: error strings should not be capitalized
